package scaffold

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/gh-xj/agent-repo-kit/cli/internal/work"
)

func ensureDocsReadmes(root, repoName string, opts Options) error {
	docs := map[string]string{
		"docs/README.md": fmt.Sprintf(`# Docs

Tracked docs root for %q. This repo uses the intent-first taxonomy declared in %q.

- %q — RFIs, asks, scope, and acceptance criteria.
- %q — design decisions and architecture choices.
- %q — executable implementation plans.
- %q — rollout notes, verification notes, and implementation reports.
- %q — stable vocabularies, schemas, and mappings.

External-source-backed material belongs in %q, not %q.

<!-- Generated by %s -->
`, repoName, ConfigPath, "requests/", "planning/", "plans/", "implementation/", "taxonomy/", ".wiki/", "docs/", ManagedMarker),
		"docs/requests/README.md": `# Requests

Store RFI and scoped-request documents here.

Filename contract: ` + "`YYYYMMDD_rfi_<topic>.md`" + `

<!-- Generated by ` + ManagedMarker + ` -->
`,
		"docs/planning/README.md": `# Planning

Store approved design and architecture documents here.

Filename contract: ` + "`YYYY-MM-DD_<topic>_design.md`" + `

<!-- Generated by ` + ManagedMarker + ` -->
`,
		"docs/plans/README.md": `# Plans

Store executable implementation plans here.

Filename contract: ` + "`YYYY-MM-DD-<topic>.md`" + `

<!-- Generated by ` + ManagedMarker + ` -->
`,
		"docs/implementation/README.md": `# Implementation

Store rollout logs, verification notes, and implementation reports here.

Filename contract: ` + "`YYYY-MM-DD_<topic>_impl_report.md`" + `

<!-- Generated by ` + ManagedMarker + ` -->
`,
		"docs/taxonomy/README.md": `# Taxonomy

Store stable domain taxonomies, schemas, and mapping notes here.

Recommended shape: ` + "`taxonomy/<domain>/<subject>.md`" + `

<!-- Generated by ` + ManagedMarker + ` -->
`,
	}

	if !hasOperation(opts.Operations, "wiki") {
		docs["docs/README.md"] = fmt.Sprintf(`# Docs

Tracked docs root for %q. This repo uses the intent-first taxonomy declared in %q.

- %q — RFIs, asks, scope, and acceptance criteria.
- %q — design decisions and architecture choices.
- %q — executable implementation plans.
- %q — rollout notes, verification notes, and implementation reports.
- %q — stable vocabularies, schemas, and mappings.

Use %q for repo-authored documentation.

<!-- Generated by %s -->
`, repoName, ConfigPath, "requests/", "planning/", "plans/", "implementation/", "taxonomy/", "docs/", ManagedMarker)
	}

	for rel, body := range docs {
		if err := writeManagedTextFile(filepath.Join(root, rel), body, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func ensureWork(root string, enabled bool) error {
	if !enabled {
		return nil
	}
	return work.New(filepath.Join(root, work.DefaultStoreDir)).Init()
}

func ensureWiki(root string, enabled bool) error {
	if !enabled {
		return nil
	}
	srcRoot, err := resolveTemplatesRoot()
	if err != nil {
		return err
	}
	src := filepath.Join(srcRoot, "wiki")
	dst := filepath.Join(root, ".wiki")
	if err := copyTemplateTree(src, dst, nil); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(dst, "raw"), 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(dst, "pages"), 0o755); err != nil {
		return err
	}
	if err := touchManagedFile(filepath.Join(dst, "raw", ".gitkeep"), 0o644); err != nil {
		return err
	}
	if err := touchManagedFile(filepath.Join(dst, "pages", ".gitkeep"), 0o644); err != nil {
		return err
	}
	return nil
}
