package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func ensureConventionSupportFiles(root, sourceRoot string, opts Options) error {
	if err := os.MkdirAll(filepath.Join(root, ".convention-engineering"), 0o755); err != nil {
		return err
	}
	if err := writeManagedTextFile(filepath.Join(root, ConventionsCheckPath), renderConventionCheckScript(sourceRoot), 0o755); err != nil {
		return err
	}
	if err := writeManagedTextFile(filepath.Join(root, ConventionsTaskfile), renderConventionTaskfile(opts), 0o644); err != nil {
		return err
	}
	return nil
}

func ensureGitignorePattern(root string, pattern string) error {
	path := filepath.Join(root, ".gitignore")
	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		return os.WriteFile(path, []byte(pattern+"\n"), 0o644)
	}

	text := string(content)
	for _, line := range strings.Split(text, "\n") {
		if strings.TrimSpace(line) == pattern {
			return nil
		}
	}
	if text != "" && !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	text += pattern + "\n"
	return os.WriteFile(path, []byte(text), 0o644)
}

func renderConventionCheckScript(sourceRoot string) string {
	// sourceRoot is preserved as a "go run" fallback for development
	// setups where ark is not yet built/installed. At runtime the
	// resolution chain is: $ARK_BINARY -> ark on $PATH -> go run
	// <sourceRoot>/../../cli/cmd/ark.
	return fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

bootstrap_source=%s
repo_kit_root=$(cd "$(dirname "$bootstrap_source")/.." && pwd)

if [ -n "${ARK_BINARY:-}" ] && [ -x "$ARK_BINARY" ]; then
  exec "$ARK_BINARY" check "$@"
fi

if command -v ark >/dev/null 2>&1; then
  exec ark check "$@"
fi

if [ -f "$repo_kit_root/cli/cmd/ark/main.go" ]; then
  exec go run -C "$repo_kit_root/cli" ./cmd/ark check "$@"
fi

printf 'ark binary not found. Set ARK_BINARY, place ark on PATH, or run ark upgrade to install it.\n' >&2
exit 1

# Generated by %s
`, shellSingleQuote(sourceRoot), ManagedMarker)
}

func shellSingleQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func renderConventionTaskfile(opts Options) string {
	lines := []string{
		`version: "3"`,
		"",
	}

	if hasOperation(opts.Operations, "wiki") {
		lines = append(lines, "includes:")
		if hasOperation(opts.Operations, "wiki") {
			lines = append(lines,
				"  wiki:",
				"    taskfile: ../.wiki/Taskfile.yml",
				"    dir: ../.wiki",
			)
		}
		lines = append(lines, "")
	}

	lines = append(lines,
		"tasks:",
	)
	if hasOperation(opts.Operations, "work") {
		lines = append(lines,
			"  work:check:",
			"    desc: Validate the repo work tracker store",
			"    cmds:",
			"      - |",
			"        if command -v work >/dev/null 2>&1; then",
			"          work --store ../.work init >/dev/null",
			"          work --store ../.work view ready --json >/dev/null",
			"        else",
			"          echo \"work binary not found; skipping .work runtime check\"",
			"        fi",
			"",
		)
	}
	lines = append(lines,
		"  check:conventions:",
		"    desc: Validate the tracked convention contract",
		"    cmds:",
		"      - bash check.sh --repo-root .. --config "+ConfigPath,
		"",
		"  verify:",
		"    desc: Run the repo convention verification gates",
		"    cmds:",
	)
	if hasOperation(opts.Operations, "work") {
		lines = append(lines, "      - task: work:check")
	}
	if hasOperation(opts.Operations, "wiki") {
		lines = append(lines, "      - task: wiki:lint")
	}
	lines = append(lines,
		"      - task: check:conventions",
		"",
		"# Generated by "+ManagedMarker,
		"",
	)
	return strings.Join(lines, "\n")
}

func ensureRootTaskfile(root string, opts Options) error {
	path := filepath.Join(root, "Taskfile.yml")
	includeBlock := []string{
		"  conventions:",
		"    taskfile: " + ConventionsTaskfile,
		"    dir: .convention-engineering",
		"    flatten: true",
	}

	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		body := []string{
			`version: "3"`,
			"",
			"includes:",
		}
		body = append(body, includeBlock...)
		if hasOperation(opts.Operations, "work") {
			body = append(body,
				"",
				"tasks:",
				"  work:",
				"    desc: Run the repo-local work CLI",
				"    cmds:",
				"      - work --store .work {{.CLI_ARGS}}",
			)
		}
		body = append(body, "")
		return os.WriteFile(path, []byte(strings.Join(body, "\n")), 0o644)
	}

	text := string(content)
	lines := strings.Split(text, "\n")
	if !containsTopLevelKey(lines, "version:") {
		lines = append([]string{`version: "3"`, ""}, lines...)
	}

	if !strings.Contains(text, ConventionsTaskfile) {
		insertAt := -1
		for i, line := range lines {
			if strings.TrimSpace(line) == "includes:" {
				insertAt = i + 1
				break
			}
		}
		if insertAt == -1 {
			if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
				lines = append(lines, "")
			}
			lines = append(lines, "includes:")
			insertAt = len(lines)
		}

		lines = append(lines[:insertAt], append(includeBlock, lines[insertAt:]...)...)
	}
	if hasOperation(opts.Operations, "work") && !strings.Contains("\n"+strings.Join(lines, "\n"), "\n  work:") {
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
			lines = append(lines, "")
		}
		taskInsertAt := -1
		for i, line := range lines {
			if strings.TrimSpace(line) == "tasks:" {
				taskInsertAt = i + 1
				break
			}
		}
		workTask := []string{
			"  work:",
			"    desc: Run the repo-local work CLI",
			"    cmds:",
			"      - work --store .work {{.CLI_ARGS}}",
		}
		if taskInsertAt == -1 {
			lines = append(lines, "tasks:")
			lines = append(lines, workTask...)
		} else {
			lines = append(lines[:taskInsertAt], append(workTask, lines[taskInsertAt:]...)...)
		}
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
}

func containsTopLevelKey(lines []string, prefix string) bool {
	for _, line := range lines {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	return false
}

func ensureAgentContractFiles(root string, opts Options) error {
	block := renderAgentConventionBlock(opts)
	for _, name := range []string{"AGENTS.md", "CLAUDE.md"} {
		path := filepath.Join(root, name)
		content, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return err
		}

		header := "# " + name + "\n\n"
		text := header
		if err == nil {
			text = string(content)
			if !strings.HasSuffix(text, "\n") {
				text += "\n"
			}
		}
		updated := upsertManagedBlock(text, block)
		if strings.TrimSpace(updated) == "" {
			updated = header + block
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func renderAgentConventionBlock(opts Options) string {
	lines := []string{
		managedBlockStart,
		"## Conventions",
		"",
		"- **Docs** — tracked repo docs live under `docs/` using the `requests/`,",
		"  `planning/`, `plans/`, `implementation/`, and `taxonomy/` folders.",
	}
	if hasOperation(opts.Operations, "work") {
		lines = append(lines,
			"- **Work** — local-first work tracker at `.work/`. The repo-local CLI is",
			"  exposed through `task work -- ...`; local state lives in the ignored",
			"  `.work/config.yaml` and `.work/items/*.yaml`. Daily commands:",
			"  `task work -- inbox`, `task work -- inbox add \"title\"`, `task work -- triage accept IN-0001`,",
			"  `task work -- view ready`, and `task work -- show W-0001`.",
		)
	}
	if hasOperation(opts.Operations, "wiki") {
		lines = append(lines,
			"- **Wiki** — LLM-maintained knowledge base at `.wiki/`. Read `.wiki/RULES.md`",
			"  for page types, frontmatter, and citation rules. Validate with",
			"  `task wiki:lint` (or `task -d .wiki lint`).",
		)
	}
	lines = append(lines,
		"- **Verification** — run `task verify` from the repo root to execute the",
		"  convention verification gate.",
		"- **Tracked contract** — `.convention-engineering.json` is the",
		"  machine-readable convention contract for this repo.",
		"",
		"Conventions are scaffolded by `agent-repo-kit` under `.convention-engineering/`.",
		managedBlockEnd,
		"",
	)
	return strings.Join(lines, "\n")
}

func upsertManagedBlock(existing, block string) string {
	start := strings.Index(existing, managedBlockStart)
	end := strings.Index(existing, managedBlockEnd)
	if start >= 0 && end >= start {
		end += len(managedBlockEnd)
		prefix := strings.TrimRight(existing[:start], "\n")
		suffix := strings.TrimLeft(existing[end:], "\n")
		switch {
		case prefix == "" && suffix == "":
			return block
		case prefix == "":
			return block + "\n" + suffix
		case suffix == "":
			return prefix + "\n\n" + block
		default:
			return prefix + "\n\n" + block + "\n" + suffix
		}
	}
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed == "" {
		return block
	}
	return trimmed + "\n\n" + block
}
