package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func ensureConventionSupportFiles(root, sourceRoot string, opts Options) error {
	if err := os.MkdirAll(filepath.Join(root, ".convention-engineering"), 0o755); err != nil {
		return err
	}
	if err := writeManagedTextFile(filepath.Join(root, ConventionsCheckPath), renderConventionCheckScript(sourceRoot), 0o755); err != nil {
		return err
	}
	if err := writeManagedTextFile(filepath.Join(root, ConventionsTaskfile), renderConventionTaskfile(opts), 0o644); err != nil {
		return err
	}
	return nil
}

func renderConventionCheckScript(sourceRoot string) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

bootstrap_source=%s
# The agent-repo-kit root is the parent of bootstrap_source (which points at
# convention-engineering/). cli/ lives alongside it.
repo_kit_root=$(dirname "$bootstrap_source")

resolve_ark_binary() {
  if [ -n "${ARK_BINARY:-}" ] && [ -x "$ARK_BINARY" ]; then
    printf '%%s\n' "$ARK_BINARY"
    return 0
  fi
  if command -v ark >/dev/null 2>&1; then
    command -v ark
    return 0
  fi
  local candidates=("$repo_kit_root/cli/bin/ark")
  if [ -n "${HOME:-}" ]; then
    candidates+=("$HOME/.claude/skills/agent-repo-kit/cli/bin/ark")
    candidates+=("$HOME/.agents/skills/agent-repo-kit/cli/bin/ark")
    candidates+=("$HOME/.codex/skills/agent-repo-kit/cli/bin/ark")
  fi
  local candidate
  for candidate in "${candidates[@]}"; do
    if [ -x "$candidate" ]; then
      printf '%%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

resolve_cli_source() {
  local candidates=("$repo_kit_root/cli")
  if [ -n "${HOME:-}" ]; then
    candidates+=("$HOME/.claude/skills/agent-repo-kit/cli")
    candidates+=("$HOME/.agents/skills/agent-repo-kit/cli")
    candidates+=("$HOME/.codex/skills/agent-repo-kit/cli")
  fi
  local candidate
  for candidate in "${candidates[@]}"; do
    if [ -f "$candidate/main.go" ]; then
      printf '%%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

if ark_bin=$(resolve_ark_binary); then
  exec "$ark_bin" check "$@"
fi

if cli_source=$(resolve_cli_source); then
  exec go run "$cli_source" check "$@"
fi

printf 'ark binary not found. Set ARK_BINARY, place ark on PATH, or install agent-repo-kit into ~/.claude/skills or ~/.agents/skills (legacy fallback: ~/.codex/skills).\n' >&2
exit 1

# Generated by %s
`, shellSingleQuote(sourceRoot), ManagedMarker)
}

func shellSingleQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func renderConventionTaskfile(opts Options) string {
	lines := []string{
		`version: "3"`,
		"",
	}

	if hasOperation(opts.Operations, "tickets") || hasOperation(opts.Operations, "wiki") {
		lines = append(lines, "includes:")
		if hasOperation(opts.Operations, "tickets") {
			lines = append(lines,
				"  tickets:",
				"    taskfile: ../.tickets/Taskfile.yml",
				"    dir: ../.tickets",
			)
		}
		if hasOperation(opts.Operations, "wiki") {
			lines = append(lines,
				"  wiki:",
				"    taskfile: ../.wiki/Taskfile.yml",
				"    dir: ../.wiki",
			)
		}
		lines = append(lines, "")
	}

	lines = append(lines,
		"tasks:",
		"  check:conventions:",
		"    desc: Validate the tracked convention contract",
		"    cmds:",
		"      - bash check.sh --repo-root .. --config "+ConfigPath,
		"",
		"  verify:",
		"    desc: Run the repo convention verification gates",
		"    cmds:",
	)
	if hasOperation(opts.Operations, "tickets") {
		lines = append(lines, "      - task: tickets:test")
	}
	if hasOperation(opts.Operations, "wiki") {
		lines = append(lines, "      - task: wiki:lint")
	}
	lines = append(lines,
		"      - task: check:conventions",
		"",
		"# Generated by "+ManagedMarker,
		"",
	)
	return strings.Join(lines, "\n")
}

func ensureRootTaskfile(root string) error {
	path := filepath.Join(root, "Taskfile.yml")
	includeBlock := []string{
		"  conventions:",
		"    taskfile: " + ConventionsTaskfile,
		"    dir: .convention-engineering",
		"    flatten: true",
	}

	content, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		body := []string{
			`version: "3"`,
			"",
			"includes:",
		}
		body = append(body, includeBlock...)
		body = append(body, "")
		return os.WriteFile(path, []byte(strings.Join(body, "\n")), 0o644)
	}

	text := string(content)
	if strings.Contains(text, ConventionsTaskfile) {
		return nil
	}

	lines := strings.Split(text, "\n")
	if !containsTopLevelKey(lines, "version:") {
		lines = append([]string{`version: "3"`, ""}, lines...)
	}

	insertAt := -1
	for i, line := range lines {
		if strings.TrimSpace(line) == "includes:" {
			insertAt = i + 1
			break
		}
	}
	if insertAt == -1 {
		if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) != "" {
			lines = append(lines, "")
		}
		lines = append(lines, "includes:")
		insertAt = len(lines)
	}

	lines = append(lines[:insertAt], append(includeBlock, lines[insertAt:]...)...)
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
}

func containsTopLevelKey(lines []string, prefix string) bool {
	for _, line := range lines {
		if strings.HasPrefix(line, prefix) {
			return true
		}
	}
	return false
}

func ensureAgentContractFiles(root string, opts Options) error {
	block := renderAgentConventionBlock(opts)
	for _, name := range []string{"AGENTS.md", "CLAUDE.md"} {
		path := filepath.Join(root, name)
		content, err := os.ReadFile(path)
		if err != nil && !os.IsNotExist(err) {
			return err
		}

		header := "# " + name + "\n\n"
		text := header
		if err == nil {
			text = string(content)
			if !strings.HasSuffix(text, "\n") {
				text += "\n"
			}
		}
		updated := upsertManagedBlock(text, block)
		if strings.TrimSpace(updated) == "" {
			updated = header + block
		}
		if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func renderAgentConventionBlock(opts Options) string {
	lines := []string{
		managedBlockStart,
		"## Conventions",
		"",
		"- **Docs** — tracked repo docs live under `docs/` using the `requests/`,",
		"  `planning/`, `plans/`, `implementation/`, and `taxonomy/` folders.",
	}
	if hasOperation(opts.Operations, "tickets") {
		lines = append(lines,
			"- **Tickets** — flat-file work tracker at `.tickets/`. Read `.tickets/README.md`",
			"  for the verb surface and `.tickets/harness/schema.yaml` for the state",
			"  machine. Daily commands:",
			"  `task -d .tickets {new|list|transition|close|test}`.",
		)
	}
	if hasOperation(opts.Operations, "wiki") {
		lines = append(lines,
			"- **Wiki** — LLM-maintained knowledge base at `.wiki/`. Read `.wiki/RULES.md`",
			"  for page types, frontmatter, and citation rules. Validate with",
			"  `task wiki:lint` (or `task -d .wiki lint`).",
		)
	}
	lines = append(lines,
		"- **Verification** — run `task verify` from the repo root to execute the",
		"  convention verification gate.",
		"- **Tracked contract** — `.convention-engineering.json` is the",
		"  machine-readable convention contract for this repo.",
		"",
		"Conventions are scaffolded by `agent-repo-kit` under `.convention-engineering/`.",
		managedBlockEnd,
		"",
	)
	return strings.Join(lines, "\n")
}

func upsertManagedBlock(existing, block string) string {
	start := strings.Index(existing, managedBlockStart)
	end := strings.Index(existing, managedBlockEnd)
	if start >= 0 && end >= start {
		end += len(managedBlockEnd)
		prefix := strings.TrimRight(existing[:start], "\n")
		suffix := strings.TrimLeft(existing[end:], "\n")
		switch {
		case prefix == "" && suffix == "":
			return block
		case prefix == "":
			return block + "\n" + suffix
		case suffix == "":
			return prefix + "\n\n" + block
		default:
			return prefix + "\n\n" + block + "\n" + suffix
		}
	}
	trimmed := strings.TrimRight(existing, "\n")
	if trimmed == "" {
		return block
	}
	return trimmed + "\n\n" + block
}
