#!/usr/bin/env bash
set -euo pipefail

bootstrap_source='/Users/xj/github/agent-repo-kit/convention-engineering'
# The agent-repo-kit root is the parent of bootstrap_source (which points at
# convention-engineering/). cli/ lives alongside it.
repo_kit_root=$(dirname "$bootstrap_source")

resolve_ark_binary() {
  if [ -n "${ARK_BINARY:-}" ] && [ -x "$ARK_BINARY" ]; then
    printf '%s\n' "$ARK_BINARY"
    return 0
  fi
  if command -v ark >/dev/null 2>&1; then
    command -v ark
    return 0
  fi
  local candidates=("$repo_kit_root/cli/bin/ark")
  if [ -n "${HOME:-}" ]; then
    candidates+=("$HOME/.claude/skills/agent-repo-kit/cli/bin/ark")
    candidates+=("$HOME/.agents/skills/agent-repo-kit/cli/bin/ark")
    candidates+=("$HOME/.codex/skills/agent-repo-kit/cli/bin/ark")
  fi
  local candidate
  for candidate in "${candidates[@]}"; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

resolve_cli_source() {
  local candidates=("$repo_kit_root/cli")
  if [ -n "${HOME:-}" ]; then
    candidates+=("$HOME/.claude/skills/agent-repo-kit/cli")
    candidates+=("$HOME/.agents/skills/agent-repo-kit/cli")
    candidates+=("$HOME/.codex/skills/agent-repo-kit/cli")
  fi
  local candidate
  for candidate in "${candidates[@]}"; do
    if [ -f "$candidate/cmd/ark/main.go" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

if ark_bin=$(resolve_ark_binary); then
  exec "$ark_bin" check "$@"
fi

if cli_source=$(resolve_cli_source); then
  exec go run -C "$cli_source" ./cmd/ark check "$@"
fi

printf 'ark binary not found. Set ARK_BINARY, place ark on PATH, or install agent-repo-kit into ~/.claude/skills or ~/.agents/skills (legacy fallback: ~/.codex/skills).\n' >&2
exit 1

# Generated by agent-repo-kit --init
