#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
repo_kit_root=$(cd "$script_dir/.." && pwd)

if [ -n "${ARK_BINARY:-}" ] && [ -x "$ARK_BINARY" ]; then
  exec "$ARK_BINARY" check "$@"
fi

if command -v ark >/dev/null 2>&1; then
  exec ark check "$@"
fi

if [ -f "$repo_kit_root/cli/cmd/ark/main.go" ]; then
  exec go run -C "$repo_kit_root/cli" ./cmd/ark check "$@"
fi

printf 'ark binary not found. Set ARK_BINARY, place ark on PATH, or run ark upgrade to install it.\n' >&2
exit 1

# Generated by agent-repo-kit --init
