// Package skillsync renders per-adapter SKILL files from canonical skill
// sources. A single SKILL.md per skill root is the source of truth; targets
// are auto-discovered from the `skills/` directory and the per-adapter
// rendering conventions baked in below. The repo-root config at
// `.agent-repo-kit.json` only names the primary skill — the one that
// renders to the top-level `adapters/<harness>/SKILL.md` instead of a
// nested per-skill path.
package skillsync

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ConfigDefaultPath is the default repo-root config location.
const ConfigDefaultPath = ".agent-repo-kit.json"

// ConfigSchemaVersion is the currently supported schema version.
const ConfigSchemaVersion = 2

// SkillsDir is the repo-root-relative directory that holds skill sources.
// Every immediate subdirectory with a SKILL.md is treated as a skill.
const SkillsDir = "skills"

// SkillRouterFilename is the canonical filename for a skill's router / entry
// doc inside a skill directory.
const SkillRouterFilename = "SKILL.md"

// SyncSentinel is the sentinel line emitted into generated adapter files so
// human editors have a clear warning that the file is regenerated by
// `ark skill sync`.
const SyncSentinel = "<!-- agent-repo-kit:skill-sync — do not edit; regenerate with `ark skill sync` -->"

// Render modes.
const (
	// ModeFrontmatterBody keeps the YAML frontmatter from the canonical
	// source and emits sentinel + body underneath. Used by harnesses
	// (Claude Code) that require the portable YAML header for skill
	// discovery.
	ModeFrontmatterBody = "frontmatter+body"

	// ModeBodyOnly strips the YAML frontmatter from the canonical source
	// and emits sentinel + body. Used by harnesses (Codex, Cursor) that
	// don't consume Claude Skills frontmatter.
	ModeBodyOnly = "body-only"
)

// adapterConvention describes how one skill renders into one adapter:
//
//   - Mode: the render mode (frontmatter vs body-only).
//   - Nested: when true the skill renders to
//     `adapters/<name>/<skill>/SKILL.md`; when false it renders flat to
//     `adapters/<name>/<skill>.md`.
//
// The primary skill overrides the nested layout into a bare
// `adapters/<name>/SKILL.md` — see planTargets.
type adapterConvention struct {
	Name   string
	Mode   string
	Nested bool
}

// adapterConventions is the full set of adapters this repo renders to,
// in a deterministic order. Adding or removing an adapter is a one-line
// change here.
var adapterConventions = []adapterConvention{
	{Name: "claude-code", Mode: ModeFrontmatterBody, Nested: true},
	{Name: "codex", Mode: ModeBodyOnly, Nested: true},
	{Name: "cursor", Mode: ModeBodyOnly, Nested: false},
}

// Config is the parsed .agent-repo-kit.json file. It is deliberately tiny:
// everything else is convention.
type Config struct {
	SchemaVersion int    `json:"schema_version"`
	PrimarySkill  string `json:"primary_skill"`
}

// Target is a single rendered file: its adapter, its absolute-or-repo-relative
// path, and the render mode.
type Target struct {
	Adapter string
	Path    string
	Mode    string
}

// Skill is one canonical source and its discovered per-adapter render targets.
type Skill struct {
	ID      string
	Source  string
	Targets []Target
}

// Plan is the fully-resolved set of skills and targets ready to render.
type Plan struct {
	Skills []Skill
}

// Drift describes a mismatch between a rendered target and the file on disk.
// Reason is one of "missing", "stale", or "parse error".
type Drift struct {
	SkillID string
	Target  Target
	Reason  string
	Diff    string
}

// LoadConfig reads and validates the repo-root config. When the file does
// not exist, a zero-value Config is returned — callers that want a primary
// skill must surface their own error.
func LoadConfig(path string) (Config, error) {
	var c Config
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return c, nil
		}
		return c, fmt.Errorf("read config %q: %w", path, err)
	}
	if err := json.Unmarshal(data, &c); err != nil {
		return c, fmt.Errorf("parse config %q: %w", path, err)
	}
	if c.SchemaVersion != ConfigSchemaVersion {
		return c, fmt.Errorf("config schema_version must be %d, got %d", ConfigSchemaVersion, c.SchemaVersion)
	}
	if c.PrimarySkill == "" {
		return c, errors.New("config primary_skill is empty")
	}
	return c, nil
}

// BuildPlan discovers skills under <repoRoot>/skills/ and expands them into
// per-adapter render targets using the baked-in adapter conventions.
func BuildPlan(repoRoot string, cfg Config) (Plan, error) {
	skillNames, err := discoverSkills(repoRoot)
	if err != nil {
		return Plan{}, err
	}
	if len(skillNames) == 0 {
		return Plan{}, fmt.Errorf("no skills found under %q", filepath.Join(repoRoot, SkillsDir))
	}
	if cfg.PrimarySkill != "" && !containsString(skillNames, cfg.PrimarySkill) {
		return Plan{}, fmt.Errorf("primary_skill %q not found under %q", cfg.PrimarySkill, filepath.Join(repoRoot, SkillsDir))
	}

	plan := Plan{Skills: make([]Skill, 0, len(skillNames))}
	for _, name := range skillNames {
		skill := Skill{
			ID:     name,
			Source: filepath.Join(SkillsDir, name, SkillRouterFilename),
		}
		for _, adapter := range adapterConventions {
			skill.Targets = append(skill.Targets, planTarget(adapter, name, name == cfg.PrimarySkill))
		}
		plan.Skills = append(plan.Skills, skill)
	}
	return plan, nil
}

// planTarget returns the render target for one skill × one adapter.
func planTarget(a adapterConvention, skillName string, primary bool) Target {
	var path string
	switch {
	case primary && a.Nested:
		// Primary skill: render to the bare top-level SKILL.md of the
		// nested-layout adapter.
		path = filepath.Join("adapters", a.Name, SkillRouterFilename)
	case a.Nested:
		path = filepath.Join("adapters", a.Name, skillName, SkillRouterFilename)
	case primary:
		// Flat adapter (cursor) with primary skill: still lives at
		// <skill>.md — cursor has no top-level SKILL.md concept.
		path = filepath.Join("adapters", a.Name, skillName+".md")
	default:
		path = filepath.Join("adapters", a.Name, skillName+".md")
	}
	return Target{Adapter: a.Name, Path: path, Mode: a.Mode}
}

// discoverSkills returns the sorted names of immediate subdirectories of
// <repoRoot>/skills/ that contain a SKILL.md file.
func discoverSkills(repoRoot string) ([]string, error) {
	skillsRoot := filepath.Join(repoRoot, SkillsDir)
	entries, err := os.ReadDir(skillsRoot)
	if err != nil {
		return nil, fmt.Errorf("read skills dir %q: %w", skillsRoot, err)
	}
	names := make([]string, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(skillsRoot, entry.Name(), SkillRouterFilename)); err != nil {
			continue
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	return names, nil
}

func containsString(s []string, target string) bool {
	for _, v := range s {
		if v == target {
			return true
		}
	}
	return false
}

// splitFrontmatter separates a YAML frontmatter block from the body. If the
// source does not start with "---\n", frontmatter is returned empty and body
// is the original input. Returned frontmatter includes its enclosing fences
// (and the trailing newline after the closing fence if present) so a caller
// can re-emit it verbatim.
//
// The closing fence must be a proper "\n---\n" line (or "\n---" at EOF) —
// a bare "\n---" elsewhere in the body (e.g. a "---%s" continuation or an
// indented block scalar that the simple substring search would otherwise
// match) is NOT accepted as a fence.
func splitFrontmatter(source []byte) (frontmatter, body []byte) {
	if !bytes.HasPrefix(source, []byte("---\n")) {
		return nil, source
	}
	// The opening "---\n" is 4 bytes; the fence search begins at offset 4.
	rest := source[4:]

	// Preferred form: closing fence followed by newline, anywhere in the body.
	if idx := bytes.Index(rest, []byte("\n---\n")); idx >= 0 {
		end := idx + 5 // consume "\n---\n"
		return source[:4+end], source[4+end:]
	}

	// Tolerated form: closing fence at end-of-file with no trailing newline.
	if bytes.HasSuffix(rest, []byte("\n---")) {
		return source, nil
	}

	return nil, source
}

// Render applies the target's mode to the canonical source bytes and returns
// the rendered file contents. The output always contains the SyncSentinel.
func Render(sourceBytes []byte, target Target) ([]byte, error) {
	switch target.Mode {
	case ModeFrontmatterBody, ModeBodyOnly:
	default:
		return nil, fmt.Errorf("render: unknown mode %q", target.Mode)
	}
	frontmatter, body := splitFrontmatter(sourceBytes)
	// Normalize body to start without a leading newline so sentinel placement
	// is predictable.
	body = bytes.TrimLeft(body, "\n")

	var buf bytes.Buffer
	switch target.Mode {
	case ModeFrontmatterBody:
		if len(frontmatter) > 0 {
			buf.Write(frontmatter)
			// Ensure the frontmatter ends with a newline so the sentinel
			// lands on its own line.
			if !bytes.HasSuffix(frontmatter, []byte("\n")) {
				buf.WriteByte('\n')
			}
			buf.WriteByte('\n')
			buf.WriteString(SyncSentinel)
			buf.WriteString("\n\n")
		} else {
			buf.WriteString(SyncSentinel)
			buf.WriteString("\n\n")
		}
		buf.Write(body)
	case ModeBodyOnly:
		buf.WriteString(SyncSentinel)
		buf.WriteString("\n\n")
		buf.Write(body)
	}
	return buf.Bytes(), nil
}

// Sync renders every target in the plan and writes the rendered bytes to
// disk, creating parent directories as needed. It stops at the first error.
func Sync(repoRoot string, plan Plan) error {
	for _, skill := range plan.Skills {
		sourcePath := resolvePath(repoRoot, skill.Source)
		src, err := os.ReadFile(sourcePath)
		if err != nil {
			return fmt.Errorf("skill %q: read source %q: %w", skill.ID, sourcePath, err)
		}
		for _, target := range skill.Targets {
			out, err := Render(src, target)
			if err != nil {
				return fmt.Errorf("skill %q target %s: render: %w", skill.ID, target.Adapter, err)
			}
			targetPath := resolvePath(repoRoot, target.Path)
			if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
				return fmt.Errorf("skill %q target %s: mkdir: %w", skill.ID, target.Adapter, err)
			}
			if err := os.WriteFile(targetPath, out, 0o644); err != nil {
				return fmt.Errorf("skill %q target %s: write %q: %w", skill.ID, target.Adapter, targetPath, err)
			}
		}
	}
	return nil
}

// Check re-renders each target in memory and compares against the file on
// disk. It reports one Drift per out-of-sync target and an empty slice when
// everything is in sync.
func Check(repoRoot string, plan Plan) ([]Drift, error) {
	var drifts []Drift
	for _, skill := range plan.Skills {
		sourcePath := resolvePath(repoRoot, skill.Source)
		src, err := os.ReadFile(sourcePath)
		if err != nil {
			// One parse-error drift per skill, skip its targets.
			drifts = append(drifts, Drift{
				SkillID: skill.ID,
				Target:  Target{Path: skill.Source},
				Reason:  "parse error",
				Diff:    fmt.Sprintf("read source: %v", err),
			})
			continue
		}
		for _, target := range skill.Targets {
			expected, err := Render(src, target)
			if err != nil {
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "parse error",
					Diff:    err.Error(),
				})
				continue
			}
			targetPath := resolvePath(repoRoot, target.Path)
			actual, err := os.ReadFile(targetPath)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					drifts = append(drifts, Drift{
						SkillID: skill.ID,
						Target:  target,
						Reason:  "missing",
					})
					continue
				}
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "parse error",
					Diff:    fmt.Sprintf("read target: %v", err),
				})
				continue
			}
			if !bytes.Equal(expected, actual) {
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "stale",
					Diff:    summarizeDiff(expected, actual),
				})
			}
		}
	}
	// Deterministic ordering: skill-id, then adapter name.
	sort.SliceStable(drifts, func(i, j int) bool {
		if drifts[i].SkillID != drifts[j].SkillID {
			return drifts[i].SkillID < drifts[j].SkillID
		}
		return drifts[i].Target.Adapter < drifts[j].Target.Adapter
	})
	return drifts, nil
}

// summarizeDiff produces a short, single-line-friendly summary of the first
// divergence between expected and actual bytes. Format:
//
//	expected <N> lines / got <M> lines; first differing line <K>: <snippet>
func summarizeDiff(expected, actual []byte) string {
	expLines := strings.Split(string(expected), "\n")
	actLines := strings.Split(string(actual), "\n")
	firstDiff := -1
	limit := len(expLines)
	if len(actLines) < limit {
		limit = len(actLines)
	}
	for i := 0; i < limit; i++ {
		if expLines[i] != actLines[i] {
			firstDiff = i
			break
		}
	}
	if firstDiff == -1 && len(expLines) != len(actLines) {
		firstDiff = limit
	}
	if firstDiff == -1 {
		return fmt.Sprintf("expected %d lines / got %d lines; byte-level mismatch", len(expLines), len(actLines))
	}
	var snippet string
	if firstDiff < len(actLines) {
		snippet = truncate(actLines[firstDiff], 80)
	} else {
		snippet = "<EOF>"
	}
	return fmt.Sprintf("expected %d lines / got %d lines; first differing line %d: %s",
		len(expLines), len(actLines), firstDiff+1, snippet)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// resolvePath joins a repo-relative path against repoRoot, leaving absolute
// inputs untouched.
func resolvePath(repoRoot, p string) string {
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(repoRoot, p)
}
