// Package skillsync renders per-adapter SKILL files from canonical skill
// sources. A single SKILL.md per skill root is the source of truth, and the
// manifest (.agent-repo-kit.json) declares the per-adapter rendering targets.
package skillsync

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// ManifestDefaultPath is the default manifest location, relative to the repo
// root.
const ManifestDefaultPath = ".agent-repo-kit.json"

// SyncSentinel is the sentinel line emitted into generated adapter files so
// human editors have a clear warning that the file is regenerated by
// `ark skill sync`.
const SyncSentinel = "<!-- agent-repo-kit:skill-sync — do not edit; regenerate with `ark skill sync` -->"

// ModeFrontmatterBody keeps the YAML frontmatter from the canonical source
// and emits sentinel + body underneath. Used for harnesses (Claude Code) that
// require the portable YAML header for skill discovery.
const ModeFrontmatterBody = "frontmatter+body"

// ModeBodyOnly strips the YAML frontmatter from the canonical source and
// emits sentinel + body. Used for harnesses (Codex, Cursor) that don't consume
// Claude Skills frontmatter.
const ModeBodyOnly = "body-only"

var (
	validAdapters = map[string]struct{}{
		"claude-code": {},
		"codex":       {},
		"cursor":      {},
	}
	validModes = map[string]struct{}{
		ModeFrontmatterBody: {},
		ModeBodyOnly:        {},
	}
)

// Manifest is the parsed .agent-repo-kit.json file.
type Manifest struct {
	SchemaVersion int     `json:"schema_version"`
	Skills        []Skill `json:"skills"`
}

// Skill is one canonical source and its per-adapter render targets.
type Skill struct {
	ID      string   `json:"id"`
	Source  string   `json:"source"`
	Targets []Target `json:"targets"`
}

// Target declares where to write a rendered adapter file and which rendering
// mode to use.
type Target struct {
	Adapter string `json:"adapter"`
	Path    string `json:"path"`
	Mode    string `json:"mode"`
}

// Drift describes a mismatch between a rendered target and the file on disk.
// Reason is one of "missing", "stale", or "parse error".
type Drift struct {
	SkillID string
	Target  Target
	Reason  string
	Diff    string
}

// LoadManifest reads and validates a manifest file. Path is absolute or
// resolved relative to the caller's cwd.
func LoadManifest(path string) (Manifest, error) {
	var m Manifest
	data, err := os.ReadFile(path)
	if err != nil {
		return m, fmt.Errorf("read manifest %q: %w", path, err)
	}
	if err := json.Unmarshal(data, &m); err != nil {
		return m, fmt.Errorf("parse manifest %q: %w", path, err)
	}
	if err := validateManifest(m); err != nil {
		return m, err
	}
	return m, nil
}

func validateManifest(m Manifest) error {
	if m.SchemaVersion != 1 {
		return fmt.Errorf("manifest schema_version must be 1, got %d", m.SchemaVersion)
	}
	if len(m.Skills) == 0 {
		return errors.New("manifest skills list is empty")
	}
	seenIDs := map[string]struct{}{}
	for i, skill := range m.Skills {
		if skill.ID == "" {
			return fmt.Errorf("manifest skills[%d]: id is empty", i)
		}
		if _, dup := seenIDs[skill.ID]; dup {
			return fmt.Errorf("manifest skills[%d]: duplicate skill id %q", i, skill.ID)
		}
		seenIDs[skill.ID] = struct{}{}
		if skill.Source == "" {
			return fmt.Errorf("manifest skills[%s]: source is empty", skill.ID)
		}
		if len(skill.Targets) == 0 {
			return fmt.Errorf("manifest skills[%s]: targets list is empty", skill.ID)
		}
		for j, t := range skill.Targets {
			if _, ok := validAdapters[t.Adapter]; !ok {
				return fmt.Errorf("manifest skills[%s].targets[%d]: unknown adapter %q (expected claude-code|codex|cursor)", skill.ID, j, t.Adapter)
			}
			if t.Path == "" {
				return fmt.Errorf("manifest skills[%s].targets[%d]: path is empty", skill.ID, j)
			}
			if _, ok := validModes[t.Mode]; !ok {
				return fmt.Errorf("manifest skills[%s].targets[%d]: unknown mode %q (expected frontmatter+body|body-only)", skill.ID, j, t.Mode)
			}
		}
	}
	return nil
}

// splitFrontmatter separates a YAML frontmatter block from the body. If the
// source does not start with "---\n", frontmatter is returned empty and body
// is the original input. Returned frontmatter includes its enclosing fences
// (and the trailing newline after the closing fence if present) so a caller
// can re-emit it verbatim.
func splitFrontmatter(source []byte) (frontmatter, body []byte) {
	if !bytes.HasPrefix(source, []byte("---\n")) {
		return nil, source
	}
	// Look for a terminating "\n---\n" after the opening fence. The opening
	// "---\n" is 4 bytes; search begins at offset 4.
	rest := source[4:]
	idx := bytes.Index(rest, []byte("\n---"))
	if idx < 0 {
		return nil, source
	}
	// The closing fence "---" lives at rest[idx+1 : idx+4].
	end := idx + 4 // relative to rest
	// Skip the trailing newline if present so body doesn't start with "\n".
	if end < len(rest) && rest[end] == '\n' {
		end++
	}
	fmEnd := 4 + end
	return source[:fmEnd], source[fmEnd:]
}

// Render applies the target's mode to the canonical source bytes and returns
// the rendered file contents. The output always contains the SyncSentinel.
func Render(sourceBytes []byte, target Target) ([]byte, error) {
	if _, ok := validModes[target.Mode]; !ok {
		return nil, fmt.Errorf("render: unknown mode %q", target.Mode)
	}
	frontmatter, body := splitFrontmatter(sourceBytes)
	// Normalize body to start without a leading newline so sentinel placement
	// is predictable.
	body = bytes.TrimLeft(body, "\n")

	var buf bytes.Buffer
	switch target.Mode {
	case ModeFrontmatterBody:
		if len(frontmatter) > 0 {
			buf.Write(frontmatter)
			// Ensure the frontmatter ends with a newline so the sentinel
			// lands on its own line.
			if !bytes.HasSuffix(frontmatter, []byte("\n")) {
				buf.WriteByte('\n')
			}
			buf.WriteByte('\n')
			buf.WriteString(SyncSentinel)
			buf.WriteString("\n\n")
		} else {
			buf.WriteString(SyncSentinel)
			buf.WriteString("\n\n")
		}
		buf.Write(body)
	case ModeBodyOnly:
		buf.WriteString(SyncSentinel)
		buf.WriteString("\n\n")
		buf.Write(body)
	}
	return buf.Bytes(), nil
}

// Sync renders every target declared in the manifest and writes the rendered
// bytes to disk, creating parent directories as needed. It stops at the first
// error.
func Sync(repoRoot string, manifest Manifest) error {
	for _, skill := range manifest.Skills {
		sourcePath := resolvePath(repoRoot, skill.Source)
		src, err := os.ReadFile(sourcePath)
		if err != nil {
			return fmt.Errorf("skill %q: read source %q: %w", skill.ID, sourcePath, err)
		}
		for _, target := range skill.Targets {
			out, err := Render(src, target)
			if err != nil {
				return fmt.Errorf("skill %q target %s: render: %w", skill.ID, target.Adapter, err)
			}
			targetPath := resolvePath(repoRoot, target.Path)
			if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
				return fmt.Errorf("skill %q target %s: mkdir: %w", skill.ID, target.Adapter, err)
			}
			if err := os.WriteFile(targetPath, out, 0o644); err != nil {
				return fmt.Errorf("skill %q target %s: write %q: %w", skill.ID, target.Adapter, targetPath, err)
			}
		}
	}
	return nil
}

// Check re-renders each target in memory and compares against the file on
// disk. It reports one Drift per out-of-sync target and an empty slice when
// everything is in sync.
func Check(repoRoot string, manifest Manifest) ([]Drift, error) {
	var drifts []Drift
	for _, skill := range manifest.Skills {
		sourcePath := resolvePath(repoRoot, skill.Source)
		src, err := os.ReadFile(sourcePath)
		if err != nil {
			// One parse-error drift per skill, skip its targets.
			drifts = append(drifts, Drift{
				SkillID: skill.ID,
				Target:  Target{Path: skill.Source},
				Reason:  "parse error",
				Diff:    fmt.Sprintf("read source: %v", err),
			})
			continue
		}
		for _, target := range skill.Targets {
			expected, err := Render(src, target)
			if err != nil {
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "parse error",
					Diff:    err.Error(),
				})
				continue
			}
			targetPath := resolvePath(repoRoot, target.Path)
			actual, err := os.ReadFile(targetPath)
			if err != nil {
				if errors.Is(err, os.ErrNotExist) {
					drifts = append(drifts, Drift{
						SkillID: skill.ID,
						Target:  target,
						Reason:  "missing",
					})
					continue
				}
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "parse error",
					Diff:    fmt.Sprintf("read target: %v", err),
				})
				continue
			}
			if !bytes.Equal(expected, actual) {
				drifts = append(drifts, Drift{
					SkillID: skill.ID,
					Target:  target,
					Reason:  "stale",
					Diff:    summarizeDiff(expected, actual),
				})
			}
		}
	}
	// Deterministic ordering: skill-id, then adapter name.
	sort.SliceStable(drifts, func(i, j int) bool {
		if drifts[i].SkillID != drifts[j].SkillID {
			return drifts[i].SkillID < drifts[j].SkillID
		}
		return drifts[i].Target.Adapter < drifts[j].Target.Adapter
	})
	return drifts, nil
}

// summarizeDiff produces a short, single-line-friendly summary of the first
// divergence between expected and actual bytes. Format:
//
//	expected <N> lines / got <M> lines; first differing line <K>: <snippet>
func summarizeDiff(expected, actual []byte) string {
	expLines := strings.Split(string(expected), "\n")
	actLines := strings.Split(string(actual), "\n")
	firstDiff := -1
	limit := len(expLines)
	if len(actLines) < limit {
		limit = len(actLines)
	}
	for i := 0; i < limit; i++ {
		if expLines[i] != actLines[i] {
			firstDiff = i
			break
		}
	}
	if firstDiff == -1 && len(expLines) != len(actLines) {
		firstDiff = limit
	}
	if firstDiff == -1 {
		return fmt.Sprintf("expected %d lines / got %d lines; byte-level mismatch", len(expLines), len(actLines))
	}
	var snippet string
	if firstDiff < len(actLines) {
		snippet = truncate(actLines[firstDiff], 80)
	} else {
		snippet = "<EOF>"
	}
	return fmt.Sprintf("expected %d lines / got %d lines; first differing line %d: %s",
		len(expLines), len(actLines), firstDiff+1, snippet)
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// resolvePath joins a manifest-relative path against repoRoot, leaving
// absolute inputs untouched.
func resolvePath(repoRoot, p string) string {
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(repoRoot, p)
}
